create table public.ordenes_trabajo (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  n_ot text null,
  constraint ordenes_trabajo_pkey primary key (id)
) TABLESPACE pg_default;

create trigger trigger_generar_n_ot BEFORE INSERT on ordenes_trabajo for EACH row
execute FUNCTION generar_n_ot ();

CREATE SEQUENCE seq_ot_numero
START 1;

CREATE OR REPLACE FUNCTION generar_n_ot()
RETURNS TRIGGER AS $$
DECLARE
    numero INTEGER;
BEGIN
    -- obtener siguiente número
    numero := nextval('seq_ot_numero');

    -- generar código
    NEW.n_ot :=
        'OM-' ||
        TO_CHAR(NOW(), 'MM') || '-' ||
        TO_CHAR(NOW(), 'YYYY') || '-' ||
        LPAD(numero::TEXT, 6, '0');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_generar_n_ot
BEFORE INSERT ON ordenes_trabajo
FOR EACH ROW
EXECUTE FUNCTION generar_n_ot();

INSERT INTO ordenes_trabajo DEFAULT VALUES;