create table public.ot_equipos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  ot_id bigint null,
  empresa text null,
  ruc text null,
  fecha_servicio date null,
  certificadora text null,
  constraint ot_equipos_pkey primary key (id),
  constraint ot_equipos_ot_id_fkey foreign KEY (ot_id) references ordenes_trabajo (id)
) TABLESPACE pg_default;