create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "user" text null,
  nombres text null,
  apellidos text null,
  dni text null,
  password text null,
  rol text null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;